//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pro1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public string UId { get; set; }
        public string PName { get; set; }
        public Nullable<decimal> PPrice { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
